---


- name: Main Playbook
  hosts: myhosts
  become: true
  tasks:

  - name: I am trying to install apache2 package and PHP
    tags: ["mainfile","web"]
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: copying my html file for my website
    tags: ["web"]
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


  - name: start apache (Ubuntu)
    tags: web
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

