---


- hosts: all
  become: true
  tasks:


  - name: I am updating repository index
    apt:
      update_cache: yes


  - name: I am trying to install apache2 package
    apt:
      name: apache2
      state: absent

  - name: Adding PHP support for apache
    apt:
      name: libapache2-mod-php
      state: absent
