---


- hosts: myhosts
  become: true
  tags: ["mainfile","filemain"]
  tasks:

  - name: I am trying to install apache2 package and PHP
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest

